import { Analytics } from "@/components/header/analytics";
import { ThemeProvider } from "@/components/structure/theme-provider";
import { CarrinhoProvider } from "@/context/CarrinhoContext";
import { Metadata } from "next";
import { Inter } from "next/font/google";
import Script from "next/script";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "LHV",
  description: "Generated by andresinho20049",
};

interface RootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="pt-BR">
      <Script
        id="ads-google-1"
        async
        src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-3617432012620885"
        crossOrigin="anonymous"
      />
      <body className={`min-h-screen ${inter.className}`}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <Analytics />

          <CarrinhoProvider>{children}</CarrinhoProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
